appVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: nginx
spec: 
  replicas: 1
  selector:
    matchables:
      app: nginx
  template:  #Pod template
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      # Run the nginx
      - name: nginx
        image: nginx:1.14
        ports:
        - containerPort: 80